import { Ban, Check, Save } from "lucide-react";
import type { FlyerItem, FlyerItemStatus, Unit } from "../../types";
import { mockIngredients } from "../../mocks/ingredients";
import { Badge } from "../common/Badge";
import { Button } from "../common/Button";

const units: Unit[] = ["g", "kg", "ml", "l", "個", "本", "袋", "パック"];
const statusLabels: Record<FlyerItemStatus, string> = { review_required: "確認待ち", approved: "承認済み", rejected: "却下", published: "公開中" };

export function OcrReviewCard({ item, onChange, onStatus }: { item: FlyerItem; onChange: (item: FlyerItem) => void; onStatus: (status: FlyerItemStatus) => void }) {
  const update = <K extends keyof FlyerItem>(key: K, value: FlyerItem[K]) => onChange({ ...item, [key]: value });
  const tone = item.status === "review_required" ? "amber" : item.status === "rejected" ? "rose" : "teal";
  return (
    <article className={`rounded-2xl border bg-white p-4 shadow-sm ${item.status === "rejected" ? "border-rose-200" : item.status === "approved" ? "border-teal-200" : "border-slate-200"}`}>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs text-slate-500">OCR ID: {item.id}</p><h2 className="font-black text-ink">{item.productNameRaw || "商品名未入力"}</h2></div><div className="flex items-center gap-2"><Badge tone={tone}>{statusLabels[item.status]}</Badge><Badge tone={item.confidence < 0.8 ? "rose" : "blue"}>信頼度 {Math.round(item.confidence * 100)}%</Badge></div></div>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="md:col-span-2"><span className="field-label">商品名</span><input className="field-input" value={item.productNameRaw} onChange={(event) => update("productNameRaw", event.target.value)} /></label><label><span className="field-label">標準食材</span><select className="field-input" value={item.ingredientId ?? ""} onChange={(event) => update("ingredientId", event.target.value || null)}><option value="">未対応</option>{mockIngredients.map((ingredient) => <option key={ingredient.id} value={ingredient.id}>{ingredient.name}</option>)}</select></label><label><span className="field-label">価格</span><input type="number" min="0" className="field-input" value={item.price ?? ""} onChange={(event) => update("price", event.target.value === "" ? null : Number(event.target.value))} /></label><label><span className="field-label">税区分</span><select className="field-input" value={item.taxType} onChange={(event) => update("taxType", event.target.value as FlyerItem["taxType"])}><option value="included">税込</option><option value="excluded">税抜</option><option value="unknown">不明</option></select></label><label><span className="field-label">内容量</span><input type="number" min="0" step="0.1" className="field-input" value={item.packageQuantity ?? ""} onChange={(event) => update("packageQuantity", event.target.value === "" ? null : Number(event.target.value))} /></label><label><span className="field-label">単位</span><select className="field-input" value={item.packageUnit ?? ""} onChange={(event) => update("packageUnit", event.target.value ? event.target.value as Unit : null)}><option value="">不明</option>{units.map((unit) => <option key={unit}>{unit}</option>)}</select></label><label><span className="field-label">信頼度</span><input type="number" min="0" max="1" step="0.01" className="field-input" value={item.confidence} onChange={(event) => update("confidence", Number(event.target.value))} /></label><label><span className="field-label">掲載開始日</span><input type="date" className="field-input" value={item.validFrom} onChange={(event) => update("validFrom", event.target.value)} /></label><label><span className="field-label">掲載終了日</span><input type="date" className="field-input" value={item.validTo} onChange={(event) => update("validTo", event.target.value)} /></label></div>
      <div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => onStatus("approved")}><Check size={16} />承認</Button><Button variant="secondary" onClick={() => onStatus("approved")}><Save size={16} />修正して承認</Button><Button variant="danger" onClick={() => onStatus("rejected")}><Ban size={16} />却下</Button></div>
    </article>
  );
}
