import { Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { useState } from "react";
import { Badge } from "../../components/common/Badge";
import { Button } from "../../components/common/Button";
import { Card } from "../../components/common/Card";
import { PageContainer } from "../../components/layout/PageContainer";
import { mockIngredients } from "../../mocks/ingredients";
import { mockRecipes } from "../../mocks/recipes";
import type { Recipe } from "../../types";
import { formatEstimatedCost } from "../../utils/format";

const blankRecipe = (): Recipe => ({ id: `recipe-${Date.now()}`, name: "", description: "", cookingTime: 10, estimatedCost: null, difficulty: "簡単", servings: 1, category: "その他", wattage: null, imageUrl: mockRecipes[0].imageUrl, tags: [], ingredients: [], instructions: [""] });

export function AdminRecipesPage() {
  const [recipes, setRecipes] = useState<Recipe[]>(mockRecipes);
  const [draft, setDraft] = useState<Recipe | null>(null);
  const save = () => { if (!draft || !draft.name.trim()) return; setRecipes((current) => current.some((item) => item.id === draft.id) ? current.map((item) => item.id === draft.id ? draft : item) : [draft, ...current]); setDraft(null); };
  const addIngredient = () => { const first = mockIngredients.find((item) => !draft?.ingredients.some((ingredient) => ingredient.ingredientId === item.id)); if (draft && first) setDraft({ ...draft, ingredients: [...draft.ingredients, { ingredientId: first.id, quantity: 1, unit: first.standardUnit }] }); };
  return <PageContainer className="max-w-none"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">RECIPES</p><h1 className="mt-2 text-3xl font-black">料理管理</h1><p className="mt-2 text-sm text-slate-600">料理と必要食材、調理手順を編集します。</p></div><Button onClick={() => setDraft(blankRecipe())}><Plus size={17} />料理を追加</Button></div>
    {draft && <Card className="mt-7 border-teal-200 p-5 sm:p-7"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{recipes.some((item) => item.id === draft.id) ? "料理を編集" : "新しい料理"}</h2><button aria-label="編集を閉じる" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" onClick={() => setDraft(null)}><X size={20} /></button></div><div className="mt-5 grid gap-4 md:grid-cols-2"><label><span className="field-label">料理名</span><input className="field-input" value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label><span className="field-label">難易度</span><select className="field-input" value={draft.difficulty} onChange={(event) => setDraft({ ...draft, difficulty: event.target.value as Recipe["difficulty"] })}><option>簡単</option><option>普通</option></select></label><label><span className="field-label">調理時間（分）</span><input type="number" min="1" className="field-input" value={draft.cookingTime} onChange={(event) => setDraft({ ...draft, cookingTime: Number(event.target.value) })} /></label><label><span className="field-label">想定金額（円・未入力可）</span><input type="number" min="0" className="field-input" value={draft.estimatedCost ?? ""} onChange={(event) => setDraft({ ...draft, estimatedCost: event.target.value === "" ? null : Number(event.target.value) })} /></label><label className="md:col-span-2"><span className="field-label">説明</span><textarea className="field-input min-h-24" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label></div>
      <section className="mt-6"><div className="flex items-center justify-between"><h3 className="font-black">必要食材</h3><Button variant="secondary" className="min-h-9 px-3 py-1.5 text-xs" onClick={addIngredient}><Plus size={14} />食材を追加</Button></div><div className="mt-3 space-y-2">{draft.ingredients.map((ingredient, index) => <div key={`${ingredient.ingredientId}-${index}`} className="grid grid-cols-[1fr_88px_74px_40px] gap-2"><select className="field-input" value={ingredient.ingredientId} onChange={(event) => { const info = mockIngredients.find((item) => item.id === event.target.value); setDraft({ ...draft, ingredients: draft.ingredients.map((item, itemIndex) => itemIndex === index ? { ...item, ingredientId: event.target.value, unit: info?.standardUnit ?? item.unit } : item) }); }}>{mockIngredients.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input aria-label="必要量" type="number" min="0" step="0.1" className="field-input" value={ingredient.quantity} onChange={(event) => setDraft({ ...draft, ingredients: draft.ingredients.map((item, itemIndex) => itemIndex === index ? { ...item, quantity: Number(event.target.value) } : item) })} /><input aria-label="単位" className="field-input" value={ingredient.unit} readOnly /><button aria-label="食材を削除" className="grid place-items-center rounded-xl text-rose-600 hover:bg-rose-50" onClick={() => setDraft({ ...draft, ingredients: draft.ingredients.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={17} /></button></div>)}</div></section>
      <section className="mt-6"><h3 className="font-black">調理手順</h3><textarea className="field-input mt-3 min-h-28" value={draft.instructions.join("\n")} onChange={(event) => setDraft({ ...draft, instructions: event.target.value.split("\n") })} placeholder="1行に1手順を入力" /></section><Button className="mt-6" onClick={save} disabled={!draft.name.trim()}><Save size={17} />料理を保存</Button></Card>}
    <div className="mt-7 overflow-x-auto rounded-2xl border bg-white shadow-card"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-4">料理</th><th className="px-4 py-4">時間</th><th className="px-4 py-4">想定金額</th><th className="px-4 py-4">難易度</th><th className="px-4 py-4">食材</th><th className="px-5 py-4 text-right">操作</th></tr></thead><tbody className="divide-y">{recipes.map((recipe) => <tr key={recipe.id} className="hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><img src={recipe.imageUrl} alt="" className="h-11 w-14 rounded-lg object-cover" /><span className="font-black">{recipe.name}</span></div></td><td className="px-4 py-4">{recipe.cookingTime}分</td><td className="px-4 py-4 font-bold">{formatEstimatedCost(recipe.estimatedCost)}</td><td className="px-4 py-4"><Badge tone={recipe.difficulty === "簡単" ? "teal" : "amber"}>{recipe.difficulty}</Badge></td><td className="px-4 py-4">{recipe.ingredients.length}品</td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button aria-label={`${recipe.name}を編集`} className="rounded-lg p-2 text-blue-700 hover:bg-blue-50" onClick={() => setDraft({ ...recipe, ingredients: recipe.ingredients.map((item) => ({ ...item })), instructions: [...recipe.instructions] })}><Pencil size={17} /></button><button aria-label={`${recipe.name}を削除`} className="rounded-lg p-2 text-rose-700 hover:bg-rose-50" onClick={() => setRecipes((current) => current.filter((item) => item.id !== recipe.id))}><Trash2 size={17} /></button></div></td></tr>)}</tbody></table></div></PageContainer>;
}
